#!/bin/sh

# TODO: print usage
# TODO: use options like `--title` and `--body` and choose 1 main argument
# (e.g. `to`) 


TITLE="MAIL: $1"
BODY="From: $2\n\n$3"

if [ "$4" -eq 1 ]; then
    notify-send -u CRITICAL "$TITLE" "$BODY"
else
    notify-send "$TITLE" "$BODY"
fi

