#!/bin/sh

# TODO: print usage
# TODO: use options like `--title` and `--body` and choose 1 main argument
# (e.g. `to`) 

# Usage: 
# `notify-newmail [MAIL_TO] [MAIL_FROM] [MAIL_SUBJECT] [MAIL_PRIORITY]`
# MAIL_PRIORITY value of 1 will be translated to CRITICAL urgency. 
# Values from 2-5 are ignored.

TITLE="MAIL: $1"
BODY="$(echo "From: $2\n\n$3" | 
    # Escape < and > only in notification body (TODO: any other escapes?) 
    awk -F '\t' '{ gsub(/</, "\\&lt;"); gsub(/>/, "\\&gt;"); print }')"
    
if [ "$4" -eq 1 ]; then
    notify-send -u CRITICAL "$TITLE" "$BODY"
else
    notify-send "$TITLE" "$BODY"
fi
