#!/bin/sh

# TODO:
# - multiple 'to' addresses: parse only until first comma (first address)
# - print usage

# Usage: 
# `parsemail [PATH_TO_MAIL_FILE]
# Returns tab-separated result in following order: 
#   TO, FROM, SUBJECT, PRIORITY

# awk commands: 
# line 1: replace first colon by tab to split into 2 columns by first colon.
# line 6: return tab-separated results

cat "${1--}" | sed 's/\t/ /g' |  # replace tabs with whitespaces first
       awk -F '\t' '
{ sub(/: /, "\t") }
$1 == "To" { to = $2 }
$1 == "From" { from = $2 }
$1 == "Subject" { subject = $2 }
$1 == "X-Priority" { priority = $2 }
END { print to "\t" from "\t" subject "\t" priority }
'
